import {
  ClothingProduct,
  WorkspaceProduct,
  Product,
  Categories,
} from '@interfaces/Products';

export const MenProducts: ClothingProduct[] = [
  {
    name: "Men's Essential Tee",
    images: ['/products/Men-0-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'M', 'XL'],
    colors: [
      {name: 'Black', hex: '#000'},
      {name: 'Willow', hex: '#908651'},
      {name: 'Charcoal', hex: '#514f56'},
      {name: 'Indigo', hex: '#324d68'},
      {name: 'Bone', hex: '#f1ece5'},
      {name: 'Port', hex: '#9d7b71'},
      {name: 'Sienna', hex: '#af8b48'},
      {name: 'Deep Forest', hex: '#2c4c48'},
    ],
    kit: {
      is: true,
      description: '8-tshirt',
    },
    desc: 'undefined2',
    price: '232.00',
  },
  {
    name: "Men's Essential Tee",
    images: ['/products/Men-1-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
      {
        name: 'bone',
        hex: '#f1ece5',
      },
      {
        name: 'gray',
        hex: '#9899a0',
      },
    ],
    kit: {
      is: true,
      description: '3-tshirt',
    },
    desc: 'undefined2',
    price: '87.00',
  },
  {
    name: "Men's Essential Tee",
    images: ['/products/Men-2-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [{name: 'Willow', hex: '#908651'}],
    desc: 'undefined2',
    price: '29.00',
  },
  {
    name: 'Voyage',
    images: ['/products/Men-3-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [{name: 'Indigo', hex: '#324d68'}],
    desc: 'undefined2',
    price: '32.00',
  },
  {
    name: "Men's Essential Tee",
    images: ['/products/Men-4-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '29.00',
  },
  {
    name: 'More Than Meets the Eye',
    images: ['/products/Men-5-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'white',
        hex: '#fff',
      },
    ],
    desc: 'undefined2',
    price: '32.00',
  },
  {
    name: "Men's Essential Tee",
    images: ['/products/Men-6-0.png'],
    category: Categories.NewArrivals,
    gender: 'Men',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [{name: 'Charcoal', hex: '#514f56'}],
    desc: 'undefined2',
    price: '29.00',
  },
];

export const WomenProducts: ClothingProduct[] = [
  {
    name: "Women's Essential Tee",
    images: [
      '/products/Women-0-0.png',
      '/products/Women-0-1.png',
      '/products/Women-1-0.png',
    ],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
      {
        name: 'Brick',
        hex: '#924741',
      },
      {
        name: 'Willow',
        hex: '#908651',
      },
      {
        name: 'Bone',
        hex: '#f1ece5',
      },
      {
        name: 'Sienna',
        hex: '#af8b48',
      },
    ],
    kit: {
      is: true,
      description: '5-tshirt',
    },
    desc: 'undefined2',
    price: '54.00',
  },
  {
    name: "Women's Essential Tee",
    images: ['/products/Women-1-1.png', '/products/Women-1-0.png'],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '29.00',
  },
  {
    name: "Women's Essential Tee",
    images: ['/products/Women-2-0.png', '/products/Women-2-1.png'],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '54.00',
  },
  {
    name: "Women's Essential Tee",
    images: ['/products/Women-3-1.png', '/products/Women-3-0.png'],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '29.00',
  },
  {
    name: "Women's Essential Tee",
    images: ['/products/Women-4-0.png', '/products/Women-4-1.png'],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '29.00',
  },
  {
    name: "Women's Essential Tee",
    images: ['/products/Women-5-1.png', '/products/Women-5-0.png'],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '29.00',
  },
  {
    name: "Women's Essential Tee",
    images: ['/products/Women-6-0.png', '/products/Women-6-1.png'],
    category: Categories.NewArrivals,
    gender: 'Women',
    sizes: ['XS', 'S', 'M', 'XL'],
    colors: [
      {
        name: 'black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    price: '54.00',
  },
];

export const WorkspaceProducts: WorkspaceProduct[] = [
  {
    name: 'The Analog Complete Kit',
    images: ['/products/Work-0-0.png'],
    category: Categories.Workspace,
    colors: [{hex: '#000', name: 'Black'}],
    desc:
      'The ultimate Analog kit.\nThis bundle includes:\n- Analog Starter Kit\n- Pen Tray (Walnut)\n- HMM Ballpoint Pen\n- Analog Travel Case (Charcoal)\n\nMeet Analog: The Simplest Productivity System. Analog is a physical companion for your digital tools that helps you prioritize and focus on your most important tasks.\n\nEach Analog Card Pack include 50 cards - enough cards to get you through an entire month (with a few extras in case you need to start over). The wood card holder keeps your Today card in front of you while the open-back design to store your completed cards. The felt case holds up to 50 cards and your favorite pen so your tasks can move with you wherever you go.\n',
    material: ['Leather', 'Wool', 'Wood', 'Plastic'],
    price: '195.00',
  },
  {
    name: 'The Analog Bundle',
    images: ['/products/Work-1-0.png'],
    category: Categories.Workspace,
    colors: [{hex: '#000', name: 'Black'}],
    desc:
      'The Analog Bundle kit.\nThis bundle includes:\n- Analog Starter Kit\n- Pen Tray (Walnut)\n\nMeet Analog: The Simplest Productivity System. Analog is a physical companion for your digital tools that helps you prioritize and focus on your most important tasks.\n\nEach Analog Card Pack include 50 cards - enough cards to get you through an entire month (with a few extras in case you need to start over). The wood card holder keeps your Today card in front of you while the open-back design to store your completed cards. The felt case holds up to 50 cards and your favorite pen so your tasks can move with you wherever you go.\n',
    material: ['Leather', 'Wool', 'Wood'],
    price: '137.00',
  },
  {
    name: 'Analog Starter Kit',
    images: ['/products/Work-2-0.png'],
    category: Categories.Workspace,
    colors: [
      {name: 'Maple', hex: '#d2b8a5'},
      {name: 'Walnut', hex: '#f3dab2'},
    ],
    desc:
      'The Analog Starter Kit includes the Wood Card Holder and 3 Analog Card Packs (50 cards each). The wood card holder keeps your Today card in front of you while the open-back design to store your completed cards and. The metal divider magnetically snaps into the base creating a shelf for easy access to your Next and Someday cards. ',
    material: ['Leather', 'Wood'],
    price: '95.00',
  },
  {
    name: 'Craft Design Technology Multifunctional Pen',
    images: ['/products/Work-3-0.png', '/products/Work-3-1.png'],
    category: Categories.Workspace,
    colors: [{hex: '#000', name: 'Black'}],
    desc: 'undefined2',
    material: 'Plastic',
    price: '64.00',
  },
  {
    name: 'Craft Design Technology Stapler',
    images: ['/products/Work-4-0.png', '/products/Work-4-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'White', hex: '#fff'}],
    desc: 'undefined2',
    material: 'Metal',
    price: '25.00',
  },
  {
    name: 'Craft Design Technology Stapler',
    images: ['/products/Work-5-0.png', '/products/Work-5-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    material: 'Metal',
    price: '25.00',
  },
  {
    name: 'Analog Cards',
    images: ['/products/Work-6-0.png'],
    category: Categories.Workspace,
    colors: [{name: 'Slate', hex: '#6b6a58'}],
    desc: 'undefined2',
    material: 'Paper',
    price: '39.00',
  },
  {
    name: 'Braun Wall Clock',
    images: ['/products/Work-7-0.png', '/products/Work-7-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '54.00',
  },
  {
    name: 'Braun Wall Clock',
    images: ['/products/Work-8-0.png', '/products/Work-8-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'White', hex: '#fff'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '54.00',
  },
  {
    name: 'Analog Wood Card Holder',
    images: ['/products/Work-9-0.png', '/products/Work-9-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Walnut', hex: '#f3dab2'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '69.00',
  },

  {
    name: 'Analog Travel Case',
    images: ['/products/Work-10-0.png'],
    category: Categories.Workspace,
    colors: [{name: 'Slate', hex: '#6b6a58'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '34.00',
  },
  {
    name: 'Analog Wood Card Holder',
    images: ['/products/Work-11-0.png'],
    category: Categories.Workspace,
    colors: [{name: 'Maple', hex: '#d2b8a5'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '69.00',
  },
  {
    name: 'Discbound Heirloom Journal',
    images: ['/products/Work-12-0.png', '/products/Work-12-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '120.00',
  },
  {
    name: 'Discbound Heirloom Journal',
    images: ['/products/Work-13-0.png', '/products/Work-13-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Natural', hex: '#ecc19e'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '120.00',
  },
  {
    name: 'HMM Ballpoint Pen',
    images: ['/products/Work-14-0.png', '/products/Work-14-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '35.00',
  },
  {
    name: 'Discbound Heirloom Journal Bundle',
    images: ['/products/Work-15-0.png', '/products/Work-15-1.png'],
    category: Categories.Workspace,
    colors: [
      {name: 'Brown', hex: '#884941'},
      {name: 'Black', hex: '#000'},
      {name: 'Neutral', hex: '#ecc19e'},
    ],
    desc: 'undefined2',
    material: 'Leather',
    price: '155.00',
  },

  {
    name: 'Premium Leather Mousepad XL',
    images: ['/products/Work-16-0.png', '/products/Work-16-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '52.00',
  },
  {
    name: 'Premium Leather Mousepad',
    images: ['/products/Work-17-0.png', '/products/Work-17-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '42.00',
  },

  {
    name: 'Discbound Heirloom Journal',
    images: ['/products/Work-18-0.png', '/products/Work-18-1.png'],
    category: Categories.Workspace,
    colors: [{name: 'Brown', hex: '#884941'}],
    desc: 'undefined2',
    material: 'Leather',
    price: '120.00',
  },
  {
    name: 'Discbound Heirloom Journal Bundle',
    images: ['/products/Work-19-0.png', '/products/Work-19-1.png'],
    category: Categories.Workspace,
    colors: [
      {name: 'Brown', hex: '#884941'},
      {name: 'Black', hex: '#000'},
      {name: 'Neutral', hex: '#ecc19e'},
    ],
    desc: 'undefined2',
    material: 'Leather',
    price: '155.00',
  },
  {
    name: 'HMM Pencil',
    images: ['/products/Work-20-0.png', '/products/Work-20-1.png'],
    category: Categories.Workspace,
    colors: [
      {name: 'Gold', hex: '#e9d69d'},
      {
        name: 'Black',
        hex: '#000',
      },
    ],
    desc: 'undefined2',
    material: 'Metal',
    price: '35.00',
  },
];

export const Accesories: WorkspaceProduct[] = [
  {
    name: 'Kinto Travel Tumbler',
    images: ['/products/Item-0-0.png'],
    category: Categories.Accesories,
    colors: [{name: 'Black', hex: '#000'}],
    desc: 'undefined2',
    price: '35.00',
    material: 'Metal',
  },
  {
    name: 'Kinto Day Off Tumbler',
    images: ['/products/Item-1-0.png', '/products/Item-1-1.png'],
    category: Categories.Accesories,
    colors: [{name: 'Khaki', hex: '#5e5f49'}],
    desc: 'undefined2',
    material: 'Metal',
    price: '38.00',
  },
  {
    name: 'Hasami Porcelain Mug',
    images: ['/products/Item-2-0.png', '/products/Item-2-1.png'],
    category: Categories.Accesories,
    colors: [{name: 'Matte Black', hex: '#353132'}],
    desc: 'undefined2',
    material: 'Ceramic',
    price: '30.00',
  },
  {
    name: 'Hasami Porcelain Mug',
    images: ['/products/Item-3-0.png', '/products/Item-3-1.png'],
    category: Categories.Accesories,
    colors: [{name: 'Natural', hex: '#b8a086'}],
    desc: 'undefined2',
    material: 'Ceramic',
    price: '30.00',
  },
];
